"""empty message

Revision ID: 1e35524eb75a
Revises: ad7806df05f8
Create Date: 2021-04-16 18:33:24.239725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e35524eb75a'
down_revision = 'ad7806df05f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_objects_subzone_id', table_name='objects')
    op.drop_table('objects')
    op.drop_table('locations')
    op.drop_column('users', 'bdate')
    op.drop_column('users', 'admin_location_id')
    op.drop_column('users', 'sex')
    op.drop_column('users', 'location_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('sex', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('admin_location_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('bdate', sa.DATE(), autoincrement=False, nullable=True))
    op.create_table('locations',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('root', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['root'], ['locations.id'], name='locations_root_fkey', onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='locations_pkey')
    )
    op.create_table('objects',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('target_image_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('asset_file', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('subzone_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='objects_pkey')
    )
    op.create_index('ix_objects_subzone_id', 'objects', ['subzone_id'], unique=False)
    # ### end Alembic commands ###
